using Lanz.MapWeaver.Generator.Models;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Text;

namespace Lanz.MapWeaver.Generator.Services;

/// <summary>
/// Generates mapper implementation source code.
/// </summary>
public sealed class CodeGenerator : ICodeGenerator
{
    private readonly ITypeResolver _typeResolver;

    public CodeGenerator(ITypeResolver typeResolver)
    {
        _typeResolver = typeResolver ?? throw new ArgumentNullException(nameof(typeResolver));
    }

    /// <inheritdoc/>
    public string GenerateMapperClass(MapperInfo mapper)
    {
        var className = mapper.Type.Name;
        var symbolDisplayFormat = SymbolDisplayFormat.FullyQualifiedFormat;

        var ns = mapper.Type.ContainingNamespace.IsGlobalNamespace
            ? null
            : mapper.Type.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if (ns is not null)
        {
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Lanz.MapWeaver.Abstraction;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {className} : global::Lanz.MapWeaver.Abstraction.IMapper");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine($"        public {className}(IServiceProvider sp)");
        sb.AppendLine("        {");
        sb.AppendLine("            _sp = sp;");
        sb.AppendLine("        }");

        foreach (var method in mapper.Methods)
        {
            GenerateMapMethod(sb, method, symbolDisplayFormat);
        }

        GenerateGenericMapMethods(sb, mapper, symbolDisplayFormat);

        sb.AppendLine("    }");

        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <inheritdoc/>
    public string GenerateServiceCollectionExtension(ImmutableArray<MapperInfo> mappers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Lanz.MapWeaver.Abstraction;");
        sb.AppendLine("using System;");
        sb.AppendLine();

        sb.AppendLine("namespace Lanz.MapWeaver.Extensions");
        sb.AppendLine("{");

        GenerateOrchestrator(sb, mappers);
        GenerateExtensionMethod(sb, mappers);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateMapMethod(StringBuilder sb, MapMethodInfo method, SymbolDisplayFormat format)
    {
        var srcName = method.SourceType.ToDisplayString(format);
        var dstName = method.TargetType.ToDisplayString(format);
        
        method.MethodName = method.IsReverse 
            ? method.MethodName.Replace("Reverse", string.Empty) 
            : method.MethodName;

        if (method.IsReverse)
        {
            sb.AppendLine($"        partial void BeforeMap({srcName} source, {dstName} dest);");
            sb.AppendLine($"        partial void AfterMap({srcName} source, {dstName} dest);");
            sb.AppendLine($"        public {dstName} {method.MethodName}({srcName} source)");
        }
        else
        {
            sb.AppendLine($"        partial void BeforeMap({srcName} source, {dstName} dest);");
            sb.AppendLine($"        partial void AfterMap({srcName} source, {dstName} dest);");
            sb.AppendLine($"        public partial {dstName} {method.MethodName}({srcName} source)");
        }
        
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) return default!;");
        sb.AppendLine($"            var dest = new {dstName}();");
        sb.AppendLine("             BeforeMap(source, dest);");

        GeneratePropertyMappings(sb, method);

        sb.AppendLine();
        sb.AppendLine($"            AfterMap(source, dest);");
        sb.AppendLine("            return dest;");
        sb.AppendLine("        }");
    }

    private void GeneratePropertyMappings(StringBuilder sb, MapMethodInfo method)
    {
        var srcProps = method.SourceType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

        var dstProps = method.TargetType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

        foreach (var dp in dstProps)
        {
            if (_typeResolver.HasAttribute(dp, "Lanz.MapWeaver.Abstraction.Attributes.MapIgnoreAttribute"))
            {
                continue;
            }

            string srcPropName = dp.Name;
            var customSource = _typeResolver.GetMapPropertySource(dp, "Lanz.MapWeaver.Abstraction.Attributes.MapPropertyAttribute");

            if (!string.IsNullOrEmpty(customSource))
            {
                srcPropName = customSource!;
            }

            var sp = _typeResolver.TryResolvePropertyPath(method.SourceType, srcPropName);
            
            // If no direct match found, try flattened property matching
            if (sp is null && string.IsNullOrEmpty(customSource))
            {
                if (_typeResolver.TryFindFlattenedPropertyMatch(method.SourceType, dp.Name, out var flattenedPath))
                {
                    srcPropName = flattenedPath!;
                    sp = _typeResolver.TryResolvePropertyPath(method.SourceType, srcPropName);
                }
            }
            
            if (sp is not null)
            {
                GeneratePropertyMapping(sb, sp, dp, srcPropName);
            }
        }
    }

    private void GeneratePropertyMapping(StringBuilder sb, IPropertySymbol sourceProperty, IPropertySymbol destProperty, string srcPropName)
    {
        string accessExpression = _typeResolver.BuildSafeAccessExpression("source", srcPropName);
        
        if (SymbolEqualityComparer.Default.Equals(sourceProperty.Type, destProperty.Type))
        {
            sb.AppendLine($"            dest.{destProperty.Name} = {accessExpression};");
        }
        else
        {
            if (_typeResolver.TryGetCollectionElementType(sourceProperty.Type, out var srcItemType) &&
                _typeResolver.TryGetCollectionElementType(destProperty.Type, out var dstItemType))
            {
                GenerateCollectionMapping(sb, sourceProperty, destProperty, dstItemType!);
            }
            else if (!_typeResolver.IsPrimitiveOrString(sourceProperty.Type))
            {
                GenerateComplexTypeMapping(sb, sourceProperty, destProperty);
            }
        }
    }

    private void GenerateCollectionMapping(StringBuilder sb, IPropertySymbol sourceProperty, IPropertySymbol destProperty, ITypeSymbol dstItemType)
    {
        var dstItemTypeName = dstItemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.AppendLine("var imapper = _sp.GetRequiredService<IMapper>();");
        sb.Append($"            dest.{destProperty.Name} = source.{sourceProperty.Name}?");
        sb.Append($".Select(item => imapper.Map<{dstItemTypeName}>(item))");

        if (destProperty.Type is IArrayTypeSymbol)
        {
            sb.AppendLine(".ToArray();");
        }
        else if (destProperty.Type.Name == "List" || 
                 destProperty.Type.Name == "IList" || 
                 destProperty.Type.Name == "ICollection")
        {
            sb.AppendLine(".ToList();");
        }
        else if (destProperty.Type.Name == "IEnumerable")
        {
            sb.AppendLine(";");
        }
        else
        {
            sb.AppendLine(".ToList(); // Warning: Defaulting to List");
        }
    }

    private void GenerateComplexTypeMapping(StringBuilder sb, IPropertySymbol sourceProperty, IPropertySymbol destProperty)
    {
        var destType = destProperty.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"            if (source.{sourceProperty.Name} is not null)");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                dest.{destProperty.Name} = _sp.GetRequiredService<IMapper>().Map<{destType}>(source.{sourceProperty.Name});");
        sb.AppendLine($"            }}");
    }

    private void GenerateGenericMapMethods(StringBuilder sb, MapperInfo mapper, SymbolDisplayFormat format)
    {
        sb.AppendLine();
        sb.AppendLine("        // --- IMapper Implementation ---");

        sb.AppendLine("        public TDestination Map<TDestination>(object source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) return default!;");
        sb.AppendLine("            var srcType = source.GetType();");
        sb.AppendLine("            var dstType = typeof(TDestination);");
        sb.AppendLine();

        foreach (var method in mapper.Methods)
        {
            var srcFull = method.SourceType.ToDisplayString(format);
            var dstFull = method.TargetType.ToDisplayString(format);

            sb.AppendLine($"            if (srcType == typeof({srcFull}) && dstType == typeof({dstFull}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                var result = {method.MethodName}(({srcFull})source);");
            sb.AppendLine("                return (TDestination)(object)result;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException($\"Mapping not registered for {srcType.Name} to {dstType.Name}\");");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Map<TDestination>((object)source!);");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Current generator implementation only supports creating new instances.");
        sb.AppendLine("            // Fallback to creating a new instance.");
        sb.AppendLine("            return Map<TSource, TDestination>(source);");
        sb.AppendLine("        }");
    }

    private void GenerateOrchestrator(StringBuilder sb, ImmutableArray<MapperInfo> mappers)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Orchestrates mapping calls across all generated profiles.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class MapWeaverOrchestrator : IMapper");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("        public MapWeaverOrchestrator(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        public TDestination Map<TDestination>(object source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) return default!;");
        sb.AppendLine("            var srcType = source.GetType();");
        sb.AppendLine("            var dstType = typeof(TDestination);");
        sb.AppendLine();

        foreach (var mapper in mappers)
        {
            var mapperType = mapper.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            foreach (var method in mapper.Methods)
            {
                var srcFull = method.SourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var dstFull = method.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"            if (srcType == typeof({srcFull}) && dstType == typeof({dstFull}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                var profile = _serviceProvider.GetRequiredService<{mapperType}>();");
                sb.AppendLine($"                return ((IMapper)profile).Map<TDestination>(source);");
                sb.AppendLine("            }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            throw new InvalidOperationException($\"No mapping configuration found for {srcType.Name} to {dstType.Name} in any profile.\");");
        sb.AppendLine("        }");

        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source)");
        sb.AppendLine("            => Map<TDestination>((object)source!);");
        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)");
        sb.AppendLine("            => Map<TDestination>((object)source!);");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void GenerateExtensionMethod(StringBuilder sb, ImmutableArray<MapperInfo> mappers)
    {
        sb.AppendLine("    public static class MapWeaverServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddMapWeaver(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var mapper in mappers)
        {
            var fullClassName = mapper.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.AddSingleton<{fullClassName}>();");
        }

        sb.AppendLine("            services.AddSingleton<IMapper, MapWeaverOrchestrator>();");

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
