using Lanz.MapWeaver.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Lanz.MapWeaver.Generator;

[Generator]
public sealed class MapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mapperCandidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidate(node),
                static (ctx, _) => GetMapperInfo(ctx))
            .Where(static m => m is not null)!;

        var mappers = mapperCandidates.Collect();

        context.RegisterSourceOutput(mappers, static (spc, mapperList) =>
        {
            foreach (var mapper in mapperList!)
            {
                GenerateMapperCode(spc, mapper);
            }
        });

        var allMappers = mapperCandidates.Collect();

        context.RegisterSourceOutput(allMappers, static (spc, mappers) =>
        {
            if (mappers.Length > 0)
            {
                GenerateServiceCollectionExtension(spc, mappers!);
            }
        });
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;

    private static MapperInfo? GetMapperInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
            return null;

        var generateMapperAttr = semanticModel.Compilation
            .GetTypeByMetadataName("Lanz.MapWeaver.Abstraction.Attributes.GenerateMapperAttribute");
        if (generateMapperAttr is null)
            return null;

        var hasAttr = classSymbol.GetAttributes()
            .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, generateMapperAttr));

        if (!hasAttr)
            return null;

        var mapTypesAttrSymbol = semanticModel.Compilation
            .GetTypeByMetadataName("Lanz.MapWeaver.Abstraction.Attributes.MapTypesAttribute");
        if (mapTypesAttrSymbol is null)
            return null;

        var methods = new List<MapMethodInfo>();

        foreach (var member in classSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            if (!member.IsPartialDefinition)
                continue;

            foreach (var attr in member.GetAttributes())
            {
                if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, mapTypesAttrSymbol))
                    continue;

                if (attr.ConstructorArguments.Length != 2)
                    continue;

                if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol src)
                    continue;
                if (attr.ConstructorArguments[1].Value is not INamedTypeSymbol dst)
                    continue;

                methods.Add(new MapMethodInfo
                {
                    SourceType = src,
                    TargetType = dst,
                    MethodName = member.Name
                });
            }
        }

        if (methods.Count == 0)
            return null;

        return new MapperInfo
        {
            Type = classSymbol,
            Methods = methods
        };
    }

    private static void GenerateMapperCode(SourceProductionContext context, MapperInfo mapper)
    {
        var className = mapper.Type.Name;
        var symbolDisplayFormat = SymbolDisplayFormat.FullyQualifiedFormat;

        // Risoluzione namespace
        var ns = mapper.Type.ContainingNamespace.IsGlobalNamespace
            ? null
            : mapper.Type.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        // AGGIUNTA: Implementazione dell'interfaccia IMapper
        // Nota: Uso il Full Name dell'interfaccia per evitare conflitti o missing usings
        sb.AppendLine($"    public partial class {className} : global::Lanz.MapWeaver.Abstraction.IMapper");
        sb.AppendLine("    {");

        // 1. Generazione dei metodi specifici (Typed Methods)
        foreach (var method in mapper.Methods)
        {
            var srcName = method.SourceType.ToDisplayString(symbolDisplayFormat);
            var dstName = method.TargetType.ToDisplayString(symbolDisplayFormat);

            sb.AppendLine($"        public partial {dstName} {method.MethodName}({srcName} source)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (source is null) return default!;");
            sb.AppendLine($"            var dest = new {dstName}();");

            var srcProps = method.SourceType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

            var dstProps = method.TargetType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);

            foreach (var dp in dstProps)
            {
                var sp = srcProps.FirstOrDefault(p => p.Name == dp.Name && SymbolEqualityComparer.Default.Equals(p.Type, dp.Type));
                if (sp is not null)
                {
                    sb.AppendLine($"            dest.{dp.Name} = source.{sp.Name};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("            return dest;");
            sb.AppendLine("        }");
        }

        // 2. Generazione dei metodi generici di IMapper (Dispatch logic)
        GenerateGenericMapMethods(sb, mapper);

        sb.AppendLine("    }"); // Chiudo classe

        if (ns is not null)
        {
            sb.AppendLine("}"); // Chiudo namespace
        }

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // NUOVO METODO: Genera il dispatching per IMapper
    private static void GenerateGenericMapMethods(StringBuilder sb, MapperInfo mapper)
    {
        var format = SymbolDisplayFormat.FullyQualifiedFormat;

        sb.AppendLine();
        sb.AppendLine("        // --- IMapper Implementation ---");

        // Implementazione: TDestination Map<TDestination>(object source)
        sb.AppendLine("        public TDestination Map<TDestination>(object source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) return default!;");
        sb.AppendLine("            var srcType = source.GetType();");
        sb.AppendLine("            var dstType = typeof(TDestination);");
        sb.AppendLine();

        // Genera un blocco IF per ogni coppia Source-Dest conosciuta
        foreach (var method in mapper.Methods)
        {
            var srcFull = method.SourceType.ToDisplayString(format);
            var dstFull = method.TargetType.ToDisplayString(format);

            // Check: if (srcType == typeof(User) && dstType == typeof(UserDto))
            sb.AppendLine($"            if (srcType == typeof({srcFull}) && dstType == typeof({dstFull}))");
            sb.AppendLine("            {");
            // Cast e chiamata al metodo specifico generato prima
            sb.AppendLine($"                var result = {method.MethodName}(({srcFull})source);");
            sb.AppendLine("                return (TDestination)(object)result;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException($\"Mapping not registered for {srcType.Name} to {dstType.Name}\");");
        sb.AppendLine("        }");

        // Implementazione: TDestination Map<TSource, TDestination>(TSource source)
        // Delega semplicemente al metodo precedente
        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Map<TDestination>((object)source!);");
        sb.AppendLine("        }");

        // Implementazione: Map su istanza esistente
        // (Attualmente non supportato dalla logica base 'new()', quindi lanciamo eccezione o deleghiamo)
        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Current generator implementation only supports creating new instances.");
        sb.AppendLine("            // Fallback to creating a new instance.");
        sb.AppendLine("            return Map<TSource, TDestination>(source);");
        sb.AppendLine("        }");
    }

    private static void GenerateServiceCollectionExtension(SourceProductionContext context, ImmutableArray<MapperInfo> mappers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Lanz.MapWeaver.Abstraction;");
        sb.AppendLine("using System;");
        sb.AppendLine();

        sb.AppendLine("namespace Lanz.MapWeaver.Extensions");
        sb.AppendLine("{");

        // --- 1. Generazione del Master Mapper (Orchestrator) ---
        // Questa classe implementa IMapper e conosce tutti i profili generati
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Orchestrates mapping calls across all generated profiles.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal sealed class MapWeaverOrchestrator : IMapper");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("        public MapWeaverOrchestrator(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _serviceProvider = serviceProvider;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Metodo Map<Dest>(object source)
        sb.AppendLine("        public TDestination Map<TDestination>(object source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null) return default!;");
        sb.AppendLine("            var srcType = source.GetType();");
        sb.AppendLine("            var dstType = typeof(TDestination);");
        sb.AppendLine();

        // Genera un IF gigante che controlla TUTTI i metodi di TUTTI i mapper
        // Esempio: if (srcType == typeof(User) && dstType == typeof(UserDto)) 
        //              return _serviceProvider.GetRequiredService<MyProfile>().Map(source);

        foreach (var mapper in mappers)
        {
            var mapperType = mapper.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            foreach (var method in mapper.Methods)
            {
                var srcFull = method.SourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var dstFull = method.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($"            if (srcType == typeof({srcFull}) && dstType == typeof({dstFull}))");
                sb.AppendLine("            {");
                // Recupera il profilo specifico dal DI container e chiama il suo metodo tipizzato (tramite cast a IMapper per semplicità o reflection-free dispatch)
                // Poiché i profili implementano IMapper, possiamo castarli e chiamare Map
                sb.AppendLine($"                var profile = _serviceProvider.GetRequiredService<{mapperType}>();");
                sb.AppendLine($"                return ((IMapper)profile).Map<TDestination>(source);");
                sb.AppendLine("            }");
            }
        }

        sb.AppendLine();
        sb.AppendLine("            throw new InvalidOperationException($\"No mapping configuration found for {srcType.Name} to {dstType.Name} in any profile.\");");
        sb.AppendLine("        }");

        // Altri metodi dell'interfaccia IMapper che delegano al metodo principale
        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source)");
        sb.AppendLine("            => Map<TDestination>((object)source!);");
        sb.AppendLine();
        sb.AppendLine("        public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)");
        sb.AppendLine("            => Map<TDestination>((object)source!); // Fallback to new instance creation");

        sb.AppendLine("    }"); // Fine classe Orchestrator
        sb.AppendLine();

        // --- 2. Generazione dell'Extension Method DI ---
        sb.AppendLine("    public static class MapWeaverServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddMapWeaver(this IServiceCollection services)");
        sb.AppendLine("        {");

        // Registra ogni singolo profilo concreto
        foreach (var mapper in mappers)
        {
            var fullClassName = mapper.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            services.AddSingleton<{fullClassName}>();");
        }

        // Registra l'Orchestrator come implementazione unica di IMapper
        sb.AppendLine("            services.AddSingleton<IMapper, MapWeaverOrchestrator>();");

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}"); // Fine Namespace

        context.AddSource("MapWeaverOrchestrator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }



}
